#!/bin/bash
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011 Ivan Tarozzi
#----------------------------------------------------------------------

# gitremoteinit: create git repository on remote host
#
# author: Ivan Tarozzi <itarozzi@gmail.com>
# date: 25/01/2011

set -u
#set -v

GITSERVER="192.168.10.100"

echo "Enter Project Name as defined in the server:"
read PRJNAME

if [ -z "$PRJNAME" ]; then
    echo "Error: empty project name not allowed"
    exit 1
fi

echo "Enter GIT Server Name [default=$GITSERVER]:"
read GITSERVER2

if [ -n "$GITSERVER2" ]; then
    GITSERVER=$GITSERVER2
fi


echo "Pushing [$PRJNAME] prj to [$GITSERVER] git server"
git remote add origin gitosis@$GITSERVER:$PRJNAME.git
git push origin master:refs/heads/master 

if [ $? -eq 0 ]; then
    echo "...................success!"
else
    echo "...................ERROR !!!"
    exit 5
fi

exit 0
