#! /bin/sh

quiet=no
while test -n "$1";
do
    case "$1" in
	--help)
	    cat <<BLA
options
  --help    this help
  --quiet   do not ask for confirmation
BLA
	    exit 0
	    ;;
	--quiet)
	    quiet=yes
	    ;;
    esac
    shift
done
if test "$quiet" = "no"; then
    echo "About to remove a lilypond installation from /home/ivan/lilypond"
    echo "Press ^C to abort, Enter to proceed"
    read junk
fi

for binary in lilypond; do
    rm /home/ivan/bin/$binary
done
rm -f /home/ivan/bin/lilypond-wrapper.guile /home/ivan/bin/lilypond-wrapper.python
rm -rf /home/ivan/lilypond
rm /home/ivan/bin/uninstall-lilypond
